version: 1
services:
  - type: web
    name: my-payment-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: MONGODB_URI
        value: 'mongodb+srv://aveshtrix:Golo%40123@cluster0.lyrkn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
